version: '3'

services:
  oraclefree-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    hostname: oraclefree-docker-extension
    ports:
      - ${SQL_CL_PORT:-59830}:7681
    volumes:
      - sqlcl_home:/home/sqlcl
    environment:
      - SQLPATH=/home/sqlcl
  oraclefree:
    image: gvenzl/oracle-free:${VERSION:-23.2-slim-faststart}
    hostname: oracle
    restart: unless-stopped
    volumes:
      - oracle-volume:/opt/oracle/oradata
    tmpfs:
      - /run
    environment:
      - "ORACLE_PASSWORD=${ORACLE_PASSWORD:-Oracle_2023}"
      - "APP_USER=${APP_USER:-scott}"
      - "APP_USER_PASSWORD=${APP_USER_PASSWORD:-tiger}"
    ports:
      - ${APP_DB_PORT:-1521}:1521

volumes:
  oracle-volume:
  sqlcl_home:
