version: '3'

services:
  oraclexe-docker-extension:
    image: ${DESKTOP_PLUGIN_IMAGE}
    hostname: oraclexe-docker-extension
    ports:
      - ${SQL_CL_PORT:-59890}:7681
    volumes:
      - sqlcl_home:/home/sqlcl
    environment:
      - SQLPATH=/home/sqlcl
  oraclexe:
    image: gvenzl/oracle-xe:${VERSION:-21.3.0-slim}
    hostname: oraclexe
    restart: unless-stopped
    volumes:
      - oracle-volume:/opt/oracle/oradata
    tmpfs:
      - /run
    environment:
      - "ORACLE_PASSWORD=${ORACLE_PASSWORD:-Oracle_2022}"
      - "APP_USER=${APP_USER:-scott}"
      - "APP_USER_PASSWORD=${APP_USER_PASSWORD:-tiger}"
    ports:
      - ${APP_DB_PORT:-1521}:1521

volumes:
  oracle-volume:
  sqlcl_home:
